apiVersion: v1
kind: Service
metadata:
  name: reservation-postgres
spec:
  selector:
    app: postgres-reservation
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
