apiVersion: v1
kind: Service
metadata:
  name: notification-postgres
spec:
  selector:
    app: postgres-notification
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
